### ISSUE TITLE
cannot compile: SPI.transfer() SPI...setMosi missing

### ISSUE THREAD

**Issue by tueddy** [zGrEaNz/PN5180_Updater#1]
Hi,

very interesting project! I want to upgrade firmware for lower power card detection (LPCD)
But i'm unable to compile. I have installed the bluepill support from this tutorial:
https://www.heise.de/developer/artikel/Keine-bittere-Pille-die-Blue-Pill-mit-ARM-Cortex-M3-4009580.html
Blink demo works fine after installing.

On compiling your firmware-updater i get several errors SPI things are undefined:
void PN5180_Firmware::Begin() {
	SPI.setMOSI(MosiPin);
	SPI.setMISO(MisoPin);
	SPI.setSCLK(SckPin);

and 
  SPI.transfer((uint8_t*)TxBuffer, TxSize);

What is the exact environment to make this work? PN5180 wiring seems fine.
I've also tried to compile using ESP8266/ESP32 but get guru mediation errors, maybe progmem?. Arduino UNO has not enough ram. Any ideas how to get this working?
Best
Dirk

**Comment by tueddy** [comment]
I finally managed to update the PN5180 firmware to version 4.0 using the official st-libraries and the st-link V2 programmer. the SPI library described in tutorial above seems incompatible.

Thank's for your great library!
Dirk

**Comment by abidxraihan** [comment]
"I've also tried to compile using ESP8266/ESP32 but get guru mediation errors, maybe progmem?"

Currently I am trying to upgrade the firmware of an ebay PN5180 reader using an ESP32 as host. Functions such as GetFirmwareVersion, SecureCommandTransceive, GetDieID works just fine. I get a guru meditation error during Firmware update. Could it be because call to SecureDownloadTransceive did not pass any data for the parameter MaxChunkSize?

**Comment by abidxraihan** [comment]
I finally managed to update the PN5180 firmware to version 4.1 using ESP32, no additional hardware or anything needed. Arduino development environment was used. 

After extensively raking through zGrEaNz's code I found minor(but crucial) programming issues. Although these issues may just be specific to ESP32 board. The guru mediation error occurred because `ChunkCounter` variable was not initialized. Also no number was passed to `MaxChunkSize` when `SecureDownloadTransceive()` was called in lie 529 of PN5180_Firmware.cpp.
